### ISSUE TITLE
[新特性期望] 追番小组件

### ISSUE THREAD

**Issue by emako** [widget-js/widgets#13]
![image](https://github.com/widget-js/widgets/assets/24737061/ff0f3204-37f5-40e4-8b70-12096fcf81c7)
类似这种小组件

**Comment by emako** [comment]
[app.zip](https://github.com/widget-js/widgets/files/11627422/app.zip)
软件这里，找的别人python311+vue做的

**Comment by rtugeek** [comment]
可以的 不过得到下个月才有时间做

**Comment by emako** [comment]
期待

**Comment by rtugeek** [comment]
@emako 已更新，重启下客户端就有了。
![](https://github.com/widget-js/hotspot/blob/master/public/images/preview_bangumi.png?raw=true)
