### ISSUE TITLE
能否添加和风天气api组件

### ISSUE THREAD

**Issue by agczsz** [widget-js/widgets#20]
想看天气，windows自带的广告太多，做成组件比较方便

**Comment by rtugeek** [comment]
更新了，先做一个简单的2x2的

**Comment by agczsz** [comment]
希望能做成这样：
![image](https://github.com/widget-js/widgets/assets/121206519/27c41d91-68f2-4fcb-9349-9a0974cc4b6d)
参照https://github.com/HaoOuBa/Joe

**Comment by rtugeek** [comment]
![image](https://github.com/widget-js/widgets/assets/6168238/0161e8b5-b97b-4bf9-82ac-3eec7c8f7fae)
为什么不早发

**Comment by rtugeek** [comment]
> 希望能做成这样： ![image](https://private-user-images.githubusercontent.com/121206519/311428090-27c41d91-68f2-4fcb-9349-9a0974cc4b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Nzc2ODMsIm5iZiI6MTcwOTk3NzM4MywicGF0aCI6Ii8xMjEyMDY1MTkvMzExNDI4MDkwLTI3YzQxZDkxLTY4ZjItNGZjYi05MzQ5LTlhMDk3NGNjNGI2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwOTQzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTJhMTE5NGI2OWE4YTVkNjQ5MDExN2EwNTdiN2UyZjQxZGY5ZjZjMmRkYjc0MDUxODhlYzJkMGEwNTc4MTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qATeMfynsZ6LWAru7zM3L8EEbOMVFwXJbeZx0OXXq4I) 参照https://github.com/HaoOuBa/Joe

这个 https://github.com/HaoOuBa/Joe 库里面没找到天气的源代码

**Comment by agczsz** [comment]
这个对不起啊，后来才想起来之前用过typeco的这个天气侧栏体验很好....😔

**Comment by agczsz** [comment]
这个对不起啊，后来才想起来之前用过typeco的这个天气侧栏体验很好....😔

**Comment by agczsz** [comment]
> > 希望能做成这样： ![image](https://private-user-images.githubusercontent.com/121206519/311428090-27c41d91-68f2-4fcb-9349-9a0974cc4b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Nzc2ODMsIm5iZiI6MTcwOTk3NzM4MywicGF0aCI6Ii8xMjEyMDY1MTkvMzExNDI4MDkwLTI3YzQxZDkxLTY4ZjItNGZjYi05MzQ5LTlhMDk3NGNjNGI2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwOTQzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTJhMTE5NGI2OWE4YTVkNjQ5MDExN2EwNTdiN2UyZjQxZGY5ZjZjMmRkYjc0MDUxODhlYzJkMGEwNTc4MTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qATeMfynsZ6LWAru7zM3L8EEbOMVFwXJbeZx0OXXq4I) 参照https://github.com/HaoOuBa/Joe
> 
> 这个 https://github.com/HaoOuBa/Joe 库里面没找到天气的源代码

代码在这/public/aside.php，这里有一段
![image](https://github.com/widget-js/widgets/assets/121206519/9e1248be-e179-4be9-813e-159cf77c15a3)
![image](https://github.com/widget-js/widgets/assets/121206519/523fe220-dc1b-4c86-8015-c75f7fcf704c)

**Comment by rtugeek** [comment]
https://github.com/rtugeek/weather

这里有源代码，可以自己动手写

**Comment by agczsz** [comment]
Finshed on pull request
