### ISSUE TITLE
Ubuntu编译

### ISSUE THREAD

**Issue by 365993104** [widget-js/widgets#22]
这个项目可以在Ubuntu24.04上构建吗？

**Comment by rtugeek** [comment]
你说的`项目`应该是指整个桌面组件的项目，这个项目分成两个部分，1.`客户端软件`，2.`前端界面`（各种组件，其实就是网页）。
1. 客户端：目前还没开源，而且目前没有支持ubuntu的计划
2. 前端界面：基本都是开源的，都是vue3项目，如果熟悉vue的话，是可以在ubuntu上构建。

**Comment by 365993104** [comment]
好的，感谢回复
